env:
  global:
   - CC_TEST_REPORTER_ID=523f04b1d7852ce83628ad67524cdfdf10b62cc25c3fbadeedfd207420fc3063
rvm:
 - 2.3.8
 - 2.6.2
before_install:
- gem update --system
- gem install bundler
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT